package model;

import jakarta.persistence.*;
import java.io.Serial;
import java.io.Serializable;

@Entity
@Table(name = "Teacher")
public class Teacher implements Serializable {
    @Serial
    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int teacherId; // Automatically generated by the database

    private String salary;

    @Column(name = "teacherName", nullable = false) // Ensure this column cannot be null
    private String teacherName;

    @ManyToOne
    @JoinColumn(name = "department_id", nullable = false) // Join column for the Department entity
    private Department department;

    // Default constructor
    public Teacher() {}

    // Parameterized constructor for initialization
    public Teacher(String salary, String teacherName, Department department) {
        this.salary = salary;
        this.teacherName = teacherName;
        this.department = department;
    }

    // Getter and Setter for teacherId
    public int getTeacherId() {
        return teacherId;
    }

    public void setTeacherId(int teacherId) {
        this.teacherId = teacherId;
    }

    // Getter and Setter for salary
    public String getSalary() {
        return salary;
    }

    public void setSalary(String salary) {
        this.salary = salary;
    }

    // Getter and Setter for teacherName
    public String getTeacherName() {
        return teacherName;
    }

    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName;
    }

    // Getter and Setter for department
    public Department getDepartment() {
        return department;
    }

    public void setDepartment(Department department) {
        this.department = department;
    }

    @Override
    public String toString() {
        return "Teacher{" +
                "teacherId=" + teacherId +
                ", salary='" + salary + '\'' +
                ", teacherName='" + teacherName + '\'' +
                ", department=" + department +
                '}';
    }
}
